# config.py
"""
Archivo de configuración para el dashboard UPCH
"""

# Universidad principal
UPCH = "UNIVERSIDAD PERUANA CAYETANO HEREDIA"

# Archivo de datos
EXCEL_FILE = "EXCEL BASE.xlsx"
SHEET_NAME = "SEGUIMIENTO"

# Lista de carreras a filtrar
CARRERAS_FILTRAR = [
    "PSICOLOGIA",
    "ENFERMERIA", 
    "ESTOMATOLOGIA",
    "INGENIERIA INFORMATICA",
    "INGENIERIA INDUSTRIAL",
    "FARMACIA Y BIOQUIMICA",
    "INGENIERIA AMBIENTAL",
    "BIOLOGIA",
    "MEDICINA VETERINARIA Y ZOOTECNIA",
    "TECNOLOGIA MEDICA EN LA ESPECIALIDAD DE LABORATORIO CLINICO Y ANATOMIA PATOLOGICA",
]

# Lista de universidades para el gráfico comparativo
UNIVERSIDADES_FILTRO = [
    "UNIVERSIDAD PERUANA DE CIENCIAS APLICADAS S.A.C.",
    "UNIVERSIDAD CIENTIFICA DEL SUR S.A.C.",
    "UNIVERSIDAD PERUANA CAYETANO HEREDIA",
    "PONTIFICIA UNIVERSIDAD CATOLICA DEL PERU",
    "UNIVERSIDAD CONTINENTAL",
    "UNIVERSIDAD DE PIURA",
    "UNIVERSIDAD DE SAN MARTIN DE PORRES",
    "UNIVERSIDAD PRIVADA SAN IGNACIO DE LOYOLA",
    "UNIVERSIDAD PERUANA UNION",
    "UNIVERSIDAD DEL PACIFICO"
]

# Mapeo de nombres largos para el gráfico
CARRERAS_MAPPING = {
    "TECNOLOGIA MEDICA EN LA ESPECIALIDAD DE LABORATORIO CLINICO Y ANATOMIA PATOLOGICA":
    "LABORATORIO CLINICO Y ANATOMIA PATOLOGICA"
}